spring.application.name=productlsit
spring.datasource.url=jdbc:postgresql://localhost:5432/productmanage
spring.datasource.username=postgres
spring.datasource.password=Jay@1910
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

